'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//text()[not(parent::script) and not(parent::style)]'
'''xpath expression to select all text in all elements except script and style'''
all_text = '//